### ISSUE TITLE
Package building with vignette fails (again) on unit2-module2

### ISSUE THREAD

**Issue by ldemaz** [agroimpacts/geospaar#3]
Something about `devtools` and `raster` have never played well together, and the failure has cropped up again (see #1).  I think the source is related to line #600, where passing a vector of functions into `lapply` for use with `cellStats` or `calc` makes it unhappy.  I keep seeming to have to toggle between passing in function names as a character vector or functions in a list.  It varies over time, and it is mystifying as to why.  It is also unclear why a vignette will knit but not build.

**Comment by ldemaz** [comment]
Note that this problem has cropped up only since upgrading to R3.5(ish)

**Comment by LLeiSong** [comment]
Hi @ldemaz , I think this is an issue of `cellStats` function. Here are a few examples for `cellStats` in help document:
```
# NOT RUN {
r <- raster(nrow=18, ncol=36)
values(r) <- runif(ncell(r)) * 10
# works for large files
cellStats(r, 'mean')
# same, but does not work for very large files
cellStats(r, mean)
# multi-layer object
cellStats(brick(r,r), mean)
# }
```
It seems function name without quotes could fail for large files, while function names with quotes won't. 
Why it only fails for build, not knit? I guess it relates to the environmental setting. I guess R assumes/allows users have smaller RAM to use to build a package. Because I also failed to knit for the same reason. My machine only has 8G RAM.

**Comment by ldemaz** [comment]
Thanks @LLeiSong for finding that.  I hadn't seen that.  The odd thing is that it varies. Sometimes I have to change it back and forth between the two. I have it all in quotes now and it is still failing to build.  Good point on the RAM assumptions for package building.  I will have a look at that.

**Comment by LLeiSong** [comment]
This sounds strange indeed. I was able to both knit and build with functions in quotes. Then I think maybe it is not a good idea to take big rasters as examples in vignette.

**Comment by LLeiSong** [comment]
Another thing might be related. Just a thought, not the case for this issue. If we put functions within a list, might namespace be a problem?

**Comment by ldemaz** [comment]
This issue has now migrated to a different problem, which is:

```
 x System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ── Column specification ────────────────────────────────────────────────────────────────────────────
E> Delimiter: ","
E> chr  (1): uuid
E> dbl  (5): x, y, season, rained, planted
E> date (1): date
E> 
E> ℹ Use `spec()` to retrieve the full column specification for this data.
E> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
E> Error: C stack usage  7970144 is too close to the limit
E> Execution halted 
```

The last error seems to be the main culprit, which might have something to do with a recursive function.  I have made most of the code static, but still need to turn off more of it.

**Comment by ldemaz** [comment]
Set `show_col_types = FALSE` also, which doesn't seem to matter

**Comment by ldemaz** [comment]
Divided the vignette into two separate ones now, and rewrote them both so that all chunks are eval=FALSE. It seems that any chunk having a `raster::` function in it will cause a C stack failure.

**Comment by ldemaz** [comment]
Although the problem that led to this issue being created initially no longer seems to be the same, closing this for now
