### ISSUE TITLE
Typo in Unit1-Module3 reading

### ISSUE THREAD

**Issue by wqtclaire** [agroimpacts/geospaar#5]
Talked and confirmed with Lyndon on 09/13 that there is a minor typo in 4.3.3.
Both #.3 and #.4 should be columns. See attachment.
![Screen Shot 2021-09-13 at 17 37 54](https://user-images.githubusercontent.com/57687744/133160296-c8837151-783f-4406-8abc-39f6fa53323b.png)

**Comment by ldemaz** [comment]
Great catch @wqtclaire thanks!
